version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - database

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker_nginx/nginx/:/etc/nginx/conf.d/

    # postgres
    database:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: apto
            POSTGRES_USER: apto_user
            POSTGRES_PASSWORD: 123Mudar!
        volumes:
            - ./:/var/www
            - ./docker_database/:/var/lib/postgresql/data
